apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-deployment
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: reverse-proxy-nginx
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: reverse-proxy-nginx
          configMap:
            name: reverse-proxy-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: NodePort
  selector:
    app: reverse-proxy
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-nginx
data:
  app.conf: |
    server {
      listen 80;

      location /app {
        proxy_pass http://example-app/;
      }
    }
